server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/polygonbazooka
    username: blasty
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect