server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/polygonbazooka
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect